apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-resource-tracker-clusterrolebinding
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: argocd-resource-tracker
    app.kubernetes.io/part-of: aargocd-resource-tracker
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: argocd-resource-tracker-clusterrole
  apiGroup: rbac.authorization.k8s.io