apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-resource-tracker-clusterrole
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: argocd-resource-tracker
    app.kubernetes.io/part-of: aargocd-resource-tracker
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]