apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-resource-tracker
  labels:
    app: argocd-resource-tracker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: argocd-resource-tracker
  template:
    metadata:
      labels:
        app: argocd-resource-tracker
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: argocd-resource-tracker
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["run", "--loglevel=debug", {{ .Values.reposerver.name }}]
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /app/config/reposerver/tls
          name: argocd-repo-server-tls
      volumes:
      - name: argocd-repo-server-tls
        secret:
          secretName: argocd-repo-server-tls
          optional: true
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
            - key: ca.crt
              path: ca.crt