apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-resource-tracker-role
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: argocd-resource-tracker
    app.kubernetes.io/part-of: aargocd-resource-tracker
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "update", "create"]