apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: argocd-resource-tracker
    app.kubernetes.io/part-of: aargocd-resource-tracker