image:
  repository: quay.io/mangaal/argocd-resource-tracker
  tag: rc-v1@sha256:74862a3a420b3c8271ce7ebd8fa1a1cc441be82293251e60b92caeee25b6c37b
  pullPolicy: Always

replicaCount: 1

serviceAccount:
  name: argocd-resource-tracker-controller

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

namespace: argocd